comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

coverage:
  status:
    patch: 
      default:
        target: 95%
        threshold: 1%
    project:
      default:
        target: 80%
        threshold: 1%
